### ISSUE TITLE
Set up new AWS account for final deployment (until next June)

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#121]
To be managed and paid for directly by the Vietnamese partner. We can use the Devseed AWS deployment as "staging," then, and then use this separate-AWS-account deployment as "production."

Sarah's putting us in touch with the Vietnamese point-of-contact for this. This POC will be able to provide us with contact information as we set the account up (or for switching it over later), and will be able to put in their billing information.

cc @matthewhanson @danielfdsilva, since you two are doing deployment, just make sure it's documented how (and ideally simple!) to redeploy it to a fresh AWS account

**Comment by danielfdsilva** [comment]
Here are the steps to setup AWS deployment. It's not difficult but it's quite long.

## AWS EC2 setup
- Create a new EC2 instance (ubuntu)
- On the security role add a rule for HTTP
- Create and download (or select existing) permission key

## Machine setup
- Ssh into the machine (`ssh -i [key.pem] ubuntu@[instance_url]`)
- Install nginx (`sudo apt-get update; sudo apt-get install -y nginx`)
- Generate the username:password for htpasswd (http://www.htaccesstools.com/htpasswd-generator/)
- Add to the file (`sudo vim /etc/nginx/.htpasswd`)
- Open nginx's default site configuration (`sudo vim /etc/nginx/sites-enabled/default`)
- Look for something like
```
    location / {
        try_files $uri $uri/ =404;
    }
```
- and change to:
```
    location / {
        try_files $uri $uri/ =404;\
        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
```
- Save file and restart nginx (`sudo service nginx restart`)
- Change ownership of the site directory (`sudo chown ubuntu:ubuntu /var/www/html`)
- Exit the machine

## Circle ci setup
- On the `.circleci/config.yml` file add your instance's url under `environment.SSH_URL`
- Create a new private key pair (`ssh-keygen -t rsa -b 4096 -C circle-ci -f deploy_key`)
- SSH into the machine
- Add the contents of `deploy_key.pub` to the machine's `authorized_keys` (vim ~/.ssh/authorized_keys)
- Exit the machine
- Go to circle ci, setup the project and go to `Settings > SSH Permissions`
- "Add SSH key" and paste the private key. Set the hostname to you instance's address (ex: `ec2-34-207-170-176.compute-1.amazonaws.com`)
- Copy the `Fingerprint` and add it to the `.circleci/config.yml` file under `add_ssh_keys.fingerprints`
- Since CircleCI will be SSHing into a machine you'll need to add an entry to the `known_hosts` file. The easiest way to do this is to look at your own `know_hosts` (`cat ~/.ssh/know_hosts`) and look for the machine's entry. (Should look something like `ec2-34-207-170-176.compute-1.amazonaws.com,34.207.170.176 ecdsa-sha2-nistp256 AAAAE2VjZHNh...`). Copy it and add it to the circle `.circleci/config.yml` under `environment.KNOWN_HOST`.

## Circle Ci file (not final)
```
# ssh-keygen -t rsa -b 4096 -C circle-ci -f deploy_key
version: 2
jobs:
  build:
    docker:
      - image: node:6

    working_directory: ~/repo

    environment:
      - DEPLOY_BRANCH: master
      - KNOWN_HOST: "INSERT_HERE"
      - SSH_URL: "INSERT_HERE"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn lint

      - add_ssh_keys:
          fingerprints:
            - "INSERT_HERE"

      - run: 
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              yarn build
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              cd build
              echo "$KNOWN_HOST" >> ~/.ssh/known_hosts
              ssh $SSH_URL rm -rf /var/www/html/*
              scp -rp ./* $SSH_URL:/var/www/html
            else
              echo "Skip deploying to AWS"
            fi
```

@mileswwatkins Does this work for our use case?
cc @matthewhanson
